[build-system]
requires = ["setuptools>=68.0.0", "wheel>=0.41.2"]
build-backend = "setuptools.build_meta"

[project]
name = "handwritten-digit-recognition"
version = "1.0.0"
requires-python = ">=3.9,<3.10"
